# Generated by Django 5.0.1 on 2024-02-06 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ne_ximik', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ne_ximik.brand', verbose_name='Бренд'),
        ),
        migrations.CreateModel(
            name='Taste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Вкус')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='ne_ximik.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Вкус',
                'verbose_name_plural': 'Вкусы',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='taste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taste', to='ne_ximik.taste', verbose_name='Вкус'),
        ),
    ]
