# Generated by Django 5.0.1 on 2024-02-07 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ne_ximik', '0004_alter_slider_options_slider_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='model_product',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Модель/Вкус/Название товара'),
        ),
    ]
