# Generated by Django 5.0.1 on 2024-02-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ne_ximik', '0005_product_model_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='taste',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Вкус'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model_product',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Модель'),
        ),
        migrations.DeleteModel(
            name='Taste',
        ),
    ]
