# Generated by Django 5.0.1 on 2024-02-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ne_ximik', '0006_alter_product_taste_alter_product_model_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание к товару'),
        ),
        migrations.DeleteModel(
            name='ProductDescription',
        ),
    ]
