# Generated by Django 5.0.1 on 2024-02-21 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ne_ximik', '0010_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
